name: Run Cypress Tests on Vercel

on:
  push:
    branches:
      - main
  workflow_dispatch:  #

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests on deployed app
        uses: cypress-io/github-action@v6
        with:
          config: baseUrl=https://sukudoro.vercel.app
